name: ladybugonarainbow
favicon: null
layout_spectrum: 0.82393
typography_spectrum: 0.71348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bab152'
    - '#363636'
    - '#ffffff'
    - '#676440'
    - '#dfdbb0'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
